# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='user_group',
            new_name='group',
        ),
    ]
